name: Chore
description: Maintenance, tooling, or housekeeping tasks
labels: ["type: chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this task needed?
    validations:
      required: true
