name: Enhancement
description: Suggest an improvement to existing functionality
labels: ["type: enhancement"]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: How does this currently work?
    validations:
      required: true
  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: What should change and how?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this improvement valuable?
    validations:
      required: true
